// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AutoService.ApiService.Data.Migrations
{
    /// <inheritdoc />
    public partial class NormalizePhoneNumbersToE164 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Prepend '+' to all phone numbers that are not already in E.164 format.
            migrationBuilder.Sql(
                """
                UPDATE people SET "PhoneNumber" = '+' || "PhoneNumber"
                WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" NOT LIKE '+%';

                UPDATE "AspNetUsers" SET "PhoneNumber" = '+' || "PhoneNumber"
                WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" NOT LIKE '+%';
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Strip the leading '+' to revert to the bare national form.
            migrationBuilder.Sql(
                """
                UPDATE people SET "PhoneNumber" = SUBSTRING("PhoneNumber", 2)
                WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" LIKE '+%';

                UPDATE "AspNetUsers" SET "PhoneNumber" = SUBSTRING("PhoneNumber", 2)
                WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" LIKE '+%';
                """);
        }
    }
}
