// <auto-generated />
using System;
using AutoService.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoService.ApiService.Data.Migrations
{
    [DbContext(typeof(AutoServiceDbContext))]
    partial class AutoServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoService.ApiService.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("VehicleId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("AutoService.ApiService.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("people", (string)null);

                    b.HasDiscriminator<string>("PersonType").HasValue("People");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("EnginePowerHp")
                        .HasColumnType("integer");

                    b.Property<int>("EngineTorqueNm")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_EnginePowerHp", "\"EnginePowerHp\" >= 0");

                            t.HasCheckConstraint("CK_Vehicles_EngineTorqueNm", "\"EngineTorqueNm\" >= 0");

                            t.HasCheckConstraint("CK_Vehicles_MileageKm", "\"MileageKm\" >= 0");

                            t.HasCheckConstraint("CK_Vehicles_Year", "\"Year\" >= 1886 AND \"Year\" <= 2100");
                        });
                });

            modelBuilder.Entity("appointmentmechanics", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId", "MechanicId");

                    b.HasIndex("MechanicId");

                    b.ToTable("appointmentmechanics", (string)null);
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Customer", b =>
                {
                    b.HasBaseType("AutoService.ApiService.Models.People");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Mechanic", b =>
                {
                    b.HasBaseType("AutoService.ApiService.Models.People");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Mechanics_Expertise_NotEmpty", "\"Expertise\" <> ''");
                        });

                    b.HasDiscriminator().HasValue("Mechanic");
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Appointment", b =>
                {
                    b.HasOne("AutoService.ApiService.Models.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoService.ApiService.Models.People", b =>
                {
                    b.OwnsOne("AutoService.ApiService.Models.UniqueTypes.FullName", "Name", b1 =>
                        {
                            b1.Property<int>("PeopleId")
                                .HasColumnType("integer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("PeopleId");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("PeopleId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Vehicle", b =>
                {
                    b.HasOne("AutoService.ApiService.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("appointmentmechanics", b =>
                {
                    b.HasOne("AutoService.ApiService.Models.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoService.ApiService.Models.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AutoService.ApiService.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
